---
fixtures:
  forge_modules:
    epel:
      repo: "puppet/epel"
      ref: "3.0.1"
    concat:
      repo: "puppetlabs/concat"
      ref: "4.0.0"
    stdlib: "puppetlabs/stdlib"
    file_concat:
      repo: "electrical/file_concat"
      ref: "1.0.1"
  symlinks:
    awscli: "#{source_dir}"
